stages:
  - deploy

deploy_logaiops:
  stage: deploy
  image: ubuntu:22.04
  # 不写tags，使用极狐平台共享runner
  before_script:
    - apt-get update -y
    - apt-get install -y openssh-client
    - mkdir -p ~/.ssh
    - cp "$SSH_PRIVATE_KEY" ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H 47.76.135.8 >> ~/.ssh/known_hosts
  script:
    - echo "hello"