demo_test:
  tags: [vm]
  script:
    - apt-get update -y
    - apt-get install -y openssh-client docker.io docker-compose-plugin
    - echo "docker executor测试"
    - docker --version
    - docker compose version
    - whoami
